target_steps: &target_steps
  docker:
    - image: circleci/rust:1.41.0
  steps:
    - checkout
    - restore_cache:
        key: v1-ssd1306-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Cargo.toml" }}
    - run: rustup self update
    - run: sudo apt install -qq python-pip
    - run: sudo pip install linkchecker
    - run: rustup default ${RUST_VERSION:-stable}
    - run: rustup component add rustfmt
    - run: cargo update
    - run: |
        SYSROOT=$(rustc --print sysroot)

        if [[ ! "$SYSROOT" =~ "$TARGET" ]]; then
          rustup target add $TARGET
        else
          echo "Target $TARGET is already installed"
        fi
    - run: ./build.sh
    - save_cache:
        key: v1-ssd1306-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Cargo.toml" }}
        paths:
          - ./target
          - /home/ubuntu/.cargo

version: 2
jobs:
  target-arm-unknown-linux-eabi:
    environment:
      - TARGET: 'arm-unknown-linux-gnueabi'
      - DISABLE_EXAMPLES: 1
    <<: *target_steps

  target-armv7-unknown-linux-gnueabihf:
    environment:
      - TARGET: 'armv7-unknown-linux-gnueabihf'
      - DISABLE_EXAMPLES: 1
    <<: *target_steps

  target-x86_64-unknown-linux-gnu:
    environment:
      - TARGET: 'x86_64-unknown-linux-gnu'
      - DISABLE_EXAMPLES: 1
    <<: *target_steps

  target-x86_64-unknown-linux-musl:
    environment:
      - TARGET: 'x86_64-unknown-linux-musl'
      - DISABLE_EXAMPLES: 1
    <<: *target_steps

  target-thumbv6m-none-eabi:
    environment:
      - TARGET: 'thumbv6m-none-eabi'
      # Disable example builds as they target thumbv7 and up
      - DISABLE_EXAMPLES: 1
    <<: *target_steps

  target-thumbv7em-none-eabi:
    environment:
      - TARGET: 'thumbv7em-none-eabi'
    <<: *target_steps

  target-thumbv7em-none-eabihf:
    environment:
      - TARGET: 'thumbv7em-none-eabihf'
    <<: *target_steps

  target-thumbv7m-none-eabi:
    environment:
      - TARGET: 'thumbv7m-none-eabi'
    <<: *target_steps

build_jobs: &build_jobs
  jobs:
    # Raspberry Pi 1
    - target-arm-unknown-linux-eabi

    # Raspberry Pi 2, 3, etc
    - target-armv7-unknown-linux-gnueabihf

    # Linux
    - target-x86_64-unknown-linux-gnu
    - target-x86_64-unknown-linux-musl

    # Bare metal
    - target-thumbv6m-none-eabi
    - target-thumbv7em-none-eabi
    - target-thumbv7em-none-eabihf
    - target-thumbv7m-none-eabi

workflows:
  version: 2
  build_all:
    <<: *build_jobs

  # Build every day
  nightly:
    <<: *build_jobs
    triggers:
      - schedule:
          cron: '0 0 * * *'
          filters:
            branches:
              only:
                - master
